import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {type: 'doc', id: 'index', label: 'Home'},
    {type: 'doc', id: 'user-guide/index', label: 'User Guide'},
    {
      type: 'category',
      label: 'API',
      items: [{type: 'autogenerated', dirName: 'api/server'}],
    },
  ],
};

export default sidebars;
